"""domain：素材层、叙事层、能力层、生成层与剪辑层的全部表。

schema 版本随之升到 2，并已在 app/persistence/migrate.py 的 REVISION_SCHEMA 登记；
不登记的话，打开旧工程时无法向用户显示「schema 1 → 2」。

Revision ID: 0002_domain
Revises: 0001_project
Create Date: 2026-08-20 14:57:45.095932
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_domain"
down_revision: str | None = "0001_project"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha1", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("meta_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_sha1"), ["sha1"], unique=False)

    op.create_table(
        "character",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("age_range", sa.String(length=50), nullable=True),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column("voice_desc", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "export_record",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("timeline_id", sa.String(length=40), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version_ids_json", sa.Text(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("export_record", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_export_record_timeline_id"), ["timeline_id"], unique=False
        )

    op.create_table(
        "location",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prop",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timeline",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("capability", sa.String(length=30), nullable=False),
        sa.Column("api_json", sa.Text(), nullable=False),
        sa.Column("bindings_json", sa.Text(), nullable=False),
        sa.Column("nodes_json", sa.Text(), nullable=True),
        sa.Column("required_nodes_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("validation_json", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_capability"), ["capability"], unique=False)

    op.create_table(
        "appearance",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("character_id", sa.String(length=40), nullable=False),
        sa.Column("parent_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("face", sa.Text(), nullable=True),
        sa.Column("hair", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("traits", sa.Text(), nullable=True),
        sa.Column("age", sa.String(length=50), nullable=True),
        sa.Column("costume", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("overrides", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["appearance.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appearance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appearance_character_id"), ["character_id"], unique=False
        )

    op.create_table(
        "asset_ref",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=False),
        sa.Column("owner_kind", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("asset_ref", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_ref_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_ref_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "location_variant",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("location_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("time_of_day", sa.String(length=50), nullable=True),
        sa.Column("weather", sa.String(length=50), nullable=True),
        sa.Column("lighting", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location_variant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_variant_location_id"), ["location_id"], unique=False
        )

    op.create_table(
        "prop_reference",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("prop_id", sa.String(length=40), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["prop_id"], ["prop.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prop_reference", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prop_reference_prop_id"), ["prop_id"], unique=False)

    op.create_table(
        "track",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("timeline_id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("index_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("muted", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["timeline_id"], ["timeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_track_timeline_id"), ["timeline_id"], unique=False)

    op.create_table(
        "transition",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("timeline_id", sa.String(length=40), nullable=False),
        sa.Column("from_clip_id", sa.String(length=40), nullable=True),
        sa.Column("to_clip_id", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["timeline_id"], ["timeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transition_timeline_id"), ["timeline_id"], unique=False
        )

    op.create_table(
        "location_reference",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("variant_id", sa.String(length=40), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=False),
        sa.Column("camera", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["variant_id"], ["location_variant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location_reference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_reference_variant_id"), ["variant_id"], unique=False
        )

    op.create_table(
        "scene",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("index_no", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("location_variant_id", sa.String(length=40), nullable=True),
        sa.Column("time_of_day", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_variant_id"], ["location_variant.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scene", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scene_index_no"), ["index_no"], unique=False)

    op.create_table(
        "sheet_version",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("appearance_id", sa.String(length=40), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["appearance_id"], ["appearance.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sheet_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sheet_version_appearance_id"), ["appearance_id"], unique=False
        )

    op.create_table(
        "timeline_clip",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("track_id", sa.String(length=40), nullable=False),
        sa.Column("shot_id", sa.String(length=40), nullable=True),
        sa.Column("version_id", sa.String(length=40), nullable=True),
        sa.Column("asset_id", sa.String(length=40), nullable=True),
        sa.Column("index_no", sa.Integer(), nullable=False),
        sa.Column("start", sa.Float(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("in_point", sa.Float(), nullable=False),
        sa.Column("out_point", sa.Float(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("timeline_clip", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_timeline_clip_shot_id"), ["shot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_timeline_clip_track_id"), ["track_id"], unique=False)

    op.create_table(
        "shot",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("scene_id", sa.String(length=40), nullable=False),
        sa.Column("index_no", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("camera", sa.String(length=50), nullable=True),
        sa.Column("movement", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("workflow_id", sa.String(length=40), nullable=True),
        sa.Column("prev_shot_id", sa.String(length=40), nullable=True),
        sa.Column("current_version_id", sa.String(length=40), nullable=True),
        sa.Column("context_overrides_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scene.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_index_no"), ["index_no"], unique=False)
        batch_op.create_index(batch_op.f("ix_shot_scene_id"), ["scene_id"], unique=False)

    op.create_table(
        "generation_version",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("shot_id", sa.String(length=40), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("asset_id", sa.String(length=40), nullable=True),
        sa.Column("workflow_id", sa.String(length=40), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("context_json", sa.Text(), nullable=True),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["shot_id"], ["shot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generation_version_shot_id"), ["shot_id"], unique=False
        )

    op.create_table(
        "job",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("shot_id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("depends_on", sa.String(length=40), nullable=True),
        sa.Column("wait_reason", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.String(length=40), nullable=True),
        sa.Column("version_id", sa.String(length=40), nullable=True),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=True),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["shot_id"], ["shot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_shot_id"), ["shot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_status"), ["status"], unique=False)

    op.create_table(
        "shot_cast",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("shot_id", sa.String(length=40), nullable=False),
        sa.Column("appearance_id", sa.String(length=40), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["appearance_id"], ["appearance.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shot_cast", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_cast_shot_id"), ["shot_id"], unique=False)

    op.create_table(
        "shot_prop",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("shot_id", sa.String(length=40), nullable=False),
        sa.Column("prop_id", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["prop_id"], ["prop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shot_prop", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_prop_shot_id"), ["shot_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot_prop", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_prop_shot_id"))

    op.drop_table("shot_prop")
    with op.batch_alter_table("shot_cast", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_cast_shot_id"))

    op.drop_table("shot_cast")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_status"))
        batch_op.drop_index(batch_op.f("ix_job_shot_id"))

    op.drop_table("job")
    with op.batch_alter_table("generation_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_version_shot_id"))

    op.drop_table("generation_version")
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_scene_id"))
        batch_op.drop_index(batch_op.f("ix_shot_index_no"))

    op.drop_table("shot")
    with op.batch_alter_table("timeline_clip", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timeline_clip_track_id"))
        batch_op.drop_index(batch_op.f("ix_timeline_clip_shot_id"))

    op.drop_table("timeline_clip")
    with op.batch_alter_table("sheet_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sheet_version_appearance_id"))

    op.drop_table("sheet_version")
    with op.batch_alter_table("scene", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scene_index_no"))

    op.drop_table("scene")
    with op.batch_alter_table("location_reference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_reference_variant_id"))

    op.drop_table("location_reference")
    with op.batch_alter_table("transition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transition_timeline_id"))

    op.drop_table("transition")
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_timeline_id"))

    op.drop_table("track")
    with op.batch_alter_table("prop_reference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prop_reference_prop_id"))

    op.drop_table("prop_reference")
    with op.batch_alter_table("location_variant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_variant_location_id"))

    op.drop_table("location_variant")
    with op.batch_alter_table("asset_ref", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_ref_owner_id"))
        batch_op.drop_index(batch_op.f("ix_asset_ref_asset_id"))

    op.drop_table("asset_ref")
    with op.batch_alter_table("appearance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appearance_character_id"))

    op.drop_table("appearance")
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_capability"))

    op.drop_table("workflow")
    op.drop_table("timeline")
    op.drop_table("story")
    op.drop_table("prop")
    op.drop_table("location")
    with op.batch_alter_table("export_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_record_timeline_id"))

    op.drop_table("export_record")
    op.drop_table("character")
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_sha1"))
        batch_op.drop_index(batch_op.f("ix_asset_kind"))

    op.drop_table("asset")
    # ### end Alembic commands ###
